### ISSUE TITLE
Unknown section M60-M79

### ISSUE THREAD

**Issue by JosephSBoyle** [StefanoTrv/simple_icd_10_CM#10]
M60-M79 does not exist in the current reivsion of ICD10 as far as I can tell[1].
The library seems to suggest that it is:

```python
>>> import simple_icd_10_cm as cm
>>> cm.get_description("M60-M79")
'Soft tissue disorders (M60-M79)'
```

When I look at icd10data.com it seems to suggest that there are 3 subsections that cover the range M60 to M79. [2]

Not sure what the fix is for this - maybe it's refreshing the data from the upstream?

[1]. https://www.icd10data.com/search?s=M60-M79
```
[ICD-10-CM Range M70-M79](https://www.icd10data.com/ICD10CM/Codes/M00-M99/M70-M79) 
Other soft tissue disorders
```
[2]
![image](https://github.com/StefanoTrv/simple_icd_10_CM/assets/48555120/d2736732-09b2-438f-8512-d209b5fc5130)

Cheers,
Joe

**Comment by JosephSBoyle** [comment]
Update I have found some other examples too

Y62-Y84,
C00-C96

**Comment by StefanoTrv** [comment]
Hi @JosephSBoyle, the situation is quite complex.

Just a short premise: the data I used is from the CDC's and the CMS's websites. The reason why I have two different sources for the data is that the data from the CDC is not (or at least it wasn't for the version of the data used in this package) complete (a few codes are missing); this, however, is not relevant to the issue at hand.

We'll look at the data from the [CDC's website](www.cdc.gov) to understand the cause of this issue. We'll use the latest version of ICD-10-CM since the issue is still there. The CDC offers a [Browser Tool for ICD-10-CM](https://icd10cmtool.cdc.gov/) that lets you browse the different codes, just like the website you used. The code "M60-M79" is missing from this tool too: while you can't search sections directly, searching for the code M60 will show that its hierarchy doesn't include the section "M60-M79", it goes directly from the section "M60-M63" to the chapter above.

Let's now take the raw data for ICD-10-CM instead. From [this page](https://www.cdc.gov/nchs/icd/Comprehensive-Listing-of-ICD-10-CM-Files.htm), click on "ICD-10-CM FY2024 XML" and then on "icd10cm-Table and Index-2024.zip". It will download a compressed folder that contains various files. We need the file "icd10cm-tabular-2024.xml", which contains an XML tree that has the whole ICD-10-CM classification. If you search for the text "M60-M79" you'll find that the section is included in this file.
Side note: the section "M60-M79" isn't included in any sectionRef element, unlike its children sections. However, the codes "Y62-Y84" and "V00-V99" have their own sectionRef elements. "V00-V99" also has **a lot of** data attached to it. The code "C00-C96" doesn't appear in a sectionRef element, but it's referenced several times in the data of other codes.

You may have noticed that calling the `cm.get_children()` function on the problematic codes returns an empty list. This is because these codes are included in the data, but they are not the parents of the sections that would naturally be their children. These codes are instead siblings of their own children, so that, for example, `cm.get_children("20")` returns _['V00-X58', **'V00-V99'**, **'V00-V09'**, 'V10-V19', 'V20-V29', ... ]_ .

To summarize, there are some sections in ICD-10-CM that are semi-hidden, because they appear in the raw version of the data but not in the applications commonly used to explore the codes. These codes are also not properly inserted in the hierarchy, since they are siblings of the subsections that they should supposedly include, and they also don't have any children.

In the end, this is a problem with the official data, and I don't see any convincing solution. Removing the sections that have no children from the tree is perhaps the most appealing solution that I could think of, but these codes sometimes have a lot of data attached to them, data that would thus be lost. Also, these are codes that actually exist in the data, so it's debatable if it would be appropriate to not include them at all. All in all, I think it might be best to leave the situation as it is and let the users decide what is better for them.

I'm sorry if I couldn't be of much help; it's something more about the classification itself than about this package. Sadly, the situation with sections is rather messy in ICD-10-CM (but it isn't that straightforward in plain ICD-10 either). I hope that I at least managed to explain well enough the source of the problem.

**Comment by JosephSBoyle** [comment]
Thanks for the explanation @StefanoTrv - that clarifies things for me a lot.

I agree that it would be weird to delete them and lose their data, especially if they do infact exist in the official data, as you mention.

I believe people can filter them using a combination of the `is_leaf` and `is_block` functions- since these are the only things which should be both blocks and leaves as I understand it.
